// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stbpihrpwboulhxkbmgg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0YnBpaHJwd2JvdWxoeGtibWdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NzAwMTksImV4cCI6MjA1ODE0NjAxOX0.v8cRLTrvIINYTME_gfUXmC6qFoRpPTn5bufMJTtG8-Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);